techworkersco/twc-site

- .gitignore
- CNAME
- _includes/footer.html
Techworkerscoalition website now up in AWS cloudfront. @samepant I'll share deployment details and creds with you at the next meeting.
> Deploy aws

- index.md
I created the feature branch off of develop.. wasn't sure how you wanted to handle it.
> slack signup link on home page goes to google form

- _layouts/default.html
removed extra closing ``</main>``
> removed extra main tag in default layout

- _config.yml
- index.md
swapped out old blog URL for the new one ahead of 4/9 meeting
> updated blog link to publication

- _includes/mailchimp-signup.html
- index.md
for more info talk to @paige_p
> Adds mayday heading and text, as well as simple signup form

- learning-club-6.md
- learning-club-7.md
re: https://techworkersco.slack.com/archives/C5UE31L4R/p1499886599120057
> add scheme to libcom.org urls

- README.md
- learning-club-1.md
- learning-club-2.md
- learning-club-3.md
- learning-club-4.md
- learning-club-5.md
- learning-club-6.md
- learning-club-7.md
- learning-club.md
Some minor fixes and tweaks for the summer learning club site. 🙏
> Minor Changes (typos/fixes)

- learning-club-5.md
Chris i had just a few minor text tweaks, can i merge this?
> Text tweaks for learning-club-5

- learning-club-5.md
> readings updates for /5

- learning-club.md
> Update to /5 title

- _includes/callout.html
- _layouts/default.html
- learning-club-5.md
- learning-club-6.md
- learning-club-7.md
- learning-club.md
- Fix broken link in Hot Autumn readings
- Remove closing discussion from schedule
- Remove Summer Learning Club callout & discuss in past tense
- Fix typos & minor changes
> Minor Changes

- metoo-sea.md
- metoo-seattle.md
Adding resources page for the Seattle #metoo event
> Add resources page for Seattle #metoo event

- DC-home.md
added line break that isn't wrong
> small tweak

- _layouts/home.html
Adds a link to the NYC site on the homepage.
> adds link to nyc to homepage

- nyc-home.md
show events in the future OR today
> show events in the future OR today

- nyc-home.md
**what does**
- twitter link was broken, and we have a local nyc one now, so update that
- add a contact form link
- use short url for event suggestion form
> fix urls, and add contact form

- _layouts/home.html
- city_local/pdx-home.md
- city_local/pdx.md
Taking a page (ha) from Berlin's https://github.com/techworkersco/twc-site/pull/116/files.
I'll update `home.html` once that's merged.
> Add a pdx-home file

- _layouts/home.html
- city_local/sf-bay-area.md
As requested, SF Bay Area local page. There seems to be pressure to get this up quickly, but more changed will be needed and can be made later.
> Add SF Bay Area local page

- _layouts/home.html
- city_local/south-florida.md
Added LA, South Florida and San Diego, 
Please have a look! Comment if I am missing a city, and you have the information handy!
> Add LA, South Florida and San Diego

- _layouts/home.html
- city_local/austin.md
Adds a page / entry for the Austin, TX Local.
> Add page for Austin, TX

- climate/strike.md
- Fix typos
- Fix formatting, indentation, heading sizes
- Clarify wording of some sentences
- Order companies alphabetically
> Fix typos & formatting, clarify wording.

- city_local/nyc.md
see title - just want to make it easier for folks to get on our mailing list
> Add mailchimp signup form to nyc homepage

- slack-thanks.md
Remove old link and add updated links
Closes #139
> slack-thanks.md: Update links and add locals

- _i18n/en.yml
As discussed on slack, the front page should better reflect that TWC has chapters in London, Berlin & Bangalore and aspires to expand more beyond the US.
The Russian translation should also be updated. The Italian is already pretty good.
> TWC is not just in the US

- city_local/nyc.md
- updates email references
- shortens blurb since half of it is in the onboarding doc already
- minor style tweaks
- link to newsletter campaign history
> Update NYC page

- fairhotel.md
example text change to test ci flow
> Change text

- city_local/london.md
Thanks for reviewing :slightly_smiling_face:
> Update London page

- stack.md
Especially as we are now all increasingly online, this includes a guide on best practices for how to run a meeting online using Stack.
I'm uncertain of where best to link to it (index? individual local pages?), but this should at least be linkable once up.
> Add a short summary of Stack, why Stack, and how to take Stack on Zoom

- _i18n/en.yml
- _i18n/it.yml
- _i18n/ru.yml
- join.md
Updates links to the new newsletter and subscribe pages.
> Link to the new newsletter project

- _i18n/en.yml
- _includes/main.scss
- index.md
- security.md
see the discussion in proj-website on the slack
adding a few links to security guides and a blurb of support for black lives matter
> add black lives matter blurb + security links

- README.md
- _config.yml
- _i18n/en.yml
- _i18n/es.yml
This is the continuation of #173, many thanks to @1-byte-man for making the initial work!
I see there's now a guide (#225), but I'll tackle that on another PR when I have more time! I've added the link to the english version for now.
> Spanish translation

- _config.yml
- _i18n/en.yml
- _i18n/fr.yml
- _i18n/fr/guide.md
French translation for Home and Community Guide pages.
> Add French translation to Home & Guide pages

- _i18n/es.yml
Fixed some bad translation, forgot about the hover attr in the security guide
> Wording changes

- _includes/head.html
- _includes/header.html
- _includes/main.scss
- _plugins/hash.rb
- city_local/nyc.md
this PR:
- fixes more issues caused by my very restrictive CSP. broke the calendar on the NYC page since we used inline scripts for that. didn't notice because we didn't have any meetings for a while but now we getting back into it, so we need to fix it
- fixed some small css issues on the NYC page. mostly just things looking a little odd on mobile
- it was pointed out that the mobile nav btn placement is weird (in the middle) so I moved it to the right hand side
> fix bugs on NYC page + small nav adjustment

- city_local/london.md
Pandemic ⇒ no in-person meetings.
> Update London's past & present regarding meetings

- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _includes/footer.html
- _includes/header.html
- _includes/main.scss
this PR gets us to a 100 accessibility score via lighthouse, with only minor changes in a few spots
> address some a11y stuff and a minor footer nit

- _i18n/en.yml
- _i18n/pt.yml
- _layouts/default.html
- guide.md
This brings website to a perfect score of 100/100/100 in lighthouse
> Update jquery and fix guide links

- .travis.yml
Upgrade Ruby to 2.7, which is what gemfile prefers
explicitly update bundler version
> Remove unused java language option

- chapter_local/nyc.md
just cleaning up the nyc page events feed. looked a bit jank on dark mode, and just some minor tweaks to the styles (specifically making descriptions scrollable so they dont take up so much vertical space)
> clean up events feed a bit

- _config.yml
- _i18n/en.yml
- _i18n/es.yml
- _i18n/fr.yml
- _i18n/pt.yml
- index.md
just adds a 'looking for a tech union?' blurb on the home page where the BLM blurb currently is. moved BLM message a little bit down, moved the security tips link into the nav
tech union blurb just links to the list corey put together. happy to link to something else if we have anything more extensive, but i feel like it's a good synopsis of the state of things
i'm sure we'll want translations, but i figure they can be done separately. or people can just push to this branch
> re-arrange content on index page a little bit

- .travis.yml
Locally I ran `gem install travis`
and then checked config file of .travis.yml with online checker https://config.travis-ci.com/explore
> Validate Travis file;

- _data/press.yml
This may reset cache that causes https://techworkerscoalition.org/press not to work, let's see 👀
> Add Emerging Tech Brew article

- _data/chapters.yaml
San Diego TWC has a new website and is closing our meetup
> remove meetup and add website for SD

- _config.yml
- _i18n/en.yml
- _includes/main.scss
- _layouts/default.html
- _unionized_workplaces/NPR-digital-media.md
- job-board.md
This is an initial stab at a job board. Hoping to get some feedback with the format before proceeding! 
No link yet but preview here: https://deploy-preview-301--techworkersco.netlify.app/job-board/
> WIP: Job Board

- _i18n/en.yml
fix link to git for contributing to workplaces list
> fix link to git for contributing to workplaces

- _config.yml
- _includes/head.html
- join.md
> Add getform.io

- _includes/head.html
- join.md
1. Remove the allow-list of getform.io as it is not used anymore. 
1. Start using netlify forms. https://docs.netlify.com/forms/setup/
> Use netlify forms

- no-tech-for-apartheid.md
Initial No Tech for Apartheid page commit.
> Initial No Tech for Apartheid page commit

- no-tech-for-apartheid.md
Most recent version as of 11/9 2:30 PM PT.
> Make updates to no-tech-for-apartheid.md

- no-tech-for-apartheid.md
> Move calls to action to top of NOTA page, format fixes

- README.md
- _config.yml
- admin/config.yml
- admin/index.html
Enable editing/adding blogs via GitHub interface
> Add Decap admin interface

- circuit-breakers/index.html
- circuit-breakers/style.css
Initially attempted to make a custom layout for Jekyll but wanted to get something working first.
Preview [here](https://deploy-preview-374--techworkersco.netlify.app/circuit-breakers)
> add standalone pages for circuit breakers

- circuit-breakers/index.html
> update circuit breakers

- circuit-breakers/index.html
Adds language that is more inviting to beginners, and a rough definition of "tech worker." We can split this into 2 PRs if we want to work on the tech worker definition a little more.
> Add beginner and tech worker language

- .github/workflows/daily_build.yml
Every 24 hours run a daily build
> run a daily build

- join.md
Adding honeypot to avoid spammy requests https://docs.netlify.com/forms/spam-filters/
> Adding honey pot

- Gemfile
- Gemfile.lock
- _data/chapters.yaml
- chapter_local/pdx/pdx.md
This PR replaces #402, please merge this one.
> updated TWC Portland chapter page

- _includes/conf.html
- circuit-breakers/index.html
- circuit-breakers/style.css
Add Call for Papers; 
1. Adjusted text to be 1rem for improved readability; 
2. Button may need adjusting
> Make text bigger and add CFP

- _data/chapters.yaml
- chapter_local/canada.md
We have reactivated the Canadian chapter
> Add Canada to chapters

- chapters.md
Follow on from #450 to remove the extra empty heading which is now on the chapters list page
> Update chapters.md: Remove extra heading

- circuit-breakers/index.html
Add times to conference, remove CFP and replace with program language.
> circuitbreakers update
