techworkersco/twc-site

join.md

When people want to join our Slack or TWC mailing list, we ask them to provide a few social handles as part of a lightweight vetting process. There have been criticism that having `Github` in the list has unintentionally alienated non-technical folks, making them think that we are trying to prevent them from joining. This PR removes `Github` and changes the phrase `personal website` to `personal blog`   — as it is probably unusual for non-technical people to have a personal website as well.
:v:

Remove Github from list of social handles

---

nyc-home.md

this PR:
- updates the nyc local description
- adds links to our onboarding doc, social media accounts and google 'events ideas' form
- styles up the calendar event list a bit more
- adds the event descriptions to the event list
- fixes a bug where an event with no location set yet would render out 'undefined' to the page
<details>
<summary>screenshot</summary>
</details>

Updates to NYC Local sub page

---

_layouts/home.html

Now that there are numerous locals and they are linked to above, it doesn't really make sense to have a main events link here. This page is still used for the Seattle link, and they are the primary users of that page.

Remove events calendar link from homepage

---

_layouts/home.html
calendar.md
city_local/seattle.md

Move Seattle from using general events page to having its own page. Remove general events page since this is no longer relevant and is not used elsewhere.

Add Seattle local page

---

README.md
city_local/berlin.md
city_local/dc.md
city_local/nyc.md
city_local/pdx.md
city_local/sf-bay-area.md

* Fix broken link in README to refer to techworkerscoalition.org
* Rename titles for all locals because "Seattle Local" alone in a tab bar is confusing; "TWC Seattle" is much more clear and is the phrasing most commonly used when speaking about locals
* Fix errant European spelling that got mixed up in American local pages

Small fixes

---

_includes/header.html
_sass/_header.scss
_sass/_variables.scss

In order to visualize the translations navigation we need to make sure the header isn't breaking on certain viewports.
Before | After
------------ | -------------

fix header break on intermediate viewport

---

city_local/london.md

We wanted to have a link to the next TWC London meeting on this page, but don't want this to keep getting out of date or have to keep bothering you with new PRs just to update this link. This has been done using a URL which will redirect on a domain I control, so I can just keep updating this to point to the latest meeting monthly/weekly as needed, without needing to keep making new PRs. Hopefully this is acceptable. Thanks! :slightly_smiling_face:

Add link to next meeting on TWC London page

---

_includes/head.html
_sass/_header.scss
script/cibuild

Tested exact same changes on `twc-site-berlin` already, and it moved our [Google Page Speed](https://developers.google.com/speed/pagespeed/insights/) score from 91 to 100

upgrade jquery,fix image path and load asynchronously

---

city_local/london.md

A group of people in the London shard worked on a zine to promote organizing in UK workplaces.

Add a link to London's zine

---

guide.md
join.md

Specifically this PR attempts to clarify a few things for new members, as well as make explicit some rules that were not widely publicized
1 - clarify that we can reject membership if you are a journalist (functionally, we already do this) and if you have a conflicting business interest (this has been a recurring issue, and we should just write it down)
2 - there is a lot of confusion about getting on the slack. and often people will submit the form with information that doesn't really help. or they will submit it multiple times when they don't hear back immediately. so i've added some text to hopefully clarify what we are looking for, and why slack confirmation might not happen right away
I figure the code of conduct thing might be debatable, so I'm happy to let this PR sit for a bit …

Add clarification to slack signup form + minor code of conduct update

---

_i18n/en.yml
_includes/main.scss
security.md

Just fulfilling a request. Adding a link to safeprotest.tips, a security site that was built with some help from TWC volunteers
also fixed a minor annoying css issue on link hover, for the security blurb on the homepage

add safe protest tips link to security page

---

city_local/london.md

I had to hunt to find the calendar link the other day; this moves it to be with the Twitter and other contact information, which I think is a more intuitive place for it to be.

London local: Move the calendar link to the other contact information

---

index.md

Nipping the 'why we organize' section because the blurb at the top of the page -- "Guided by our vision for an inclusive & equitable tech industry, TWC organizes to build worker power through rank & file self-organization and education" -- is clear & compelling, and makes it redundant. Also, without this section, 'who we are' flows nicely into 'who we support'.

minor edit for focus

---

join.md

does what the title says + i updated the form copy a little bit more
hopefully will reduce signup confusion and divert some manager types to the ally slack

add link to managers and allies slack on join form page

---

_plugins/get_json.rb

Reduce build time from 14 to 12 seconds (and more importantly, number of external HTTP calls)

Add counter to run only once, instead of per language (even if unused)

---

_includes/head.html

**feel free to review but dont merge yet**
seattle uses an iframe to embed their events calendar, which is busted since it's not a whitelisted url
not really a big deal since it's been inactive for a long time (they stopped publicizing their meetings for a bit) but needs to be fixed if they want to make their meetings public again

fix broken seattle calendar

---

join.md

I changed wheelie to always post to slack, so there's no further need for this checkbox...it came from back when we provided different sign up options to ppl.

fix: remove superfluous slack checkbox in signup

---

.gitignore

Revert #272 
The cache of the `_site/` output seems to not change since the .gitignored was updated, see logs https://travis-ci.org/github/techworkersco/twc-site/builds/752648883

TravisCI possibly uses these for deployments?

---

404.md

Currently only explicit /404.html page works
Either this or `permalink: /404/` will fix the page

Fix 404 page to actually be used

---

_includes/header.html

see title. i just moved the `page.namespace` check farther in
the way it's setup now, the nav button remains visible no matter what. but the hidden nav is not rendered. which means that when you click it anywhere but the main 2 pages, you get nothing, even if there's a translation for that page
moving it in means it always at least renders the current language, but will also now actually render any other languages available for that specific page

fixes minor lang nav bug

---

_includes/collective-actions.html

Remove whitespacing between sources in collective-actions

---

_includes/main.scss
join.md

See title: the link to join the manager/allies slack expired. I replaced it with a link that shouldn't expire.
Also, in an effort to cut down on people submitting the form multiple times I made the requirements large and hard to ignore

fix expired allies slack link

---

.travis.yml

This readds jdk8 as java version, which the s3-website gem needs to push
https://docs.travis-ci.com/user/reference/focal/#jvm-clojure-groovy-java-scala-support

Change from default jdk for Focal and Xenial

---

_workplaces/Democracy-Works.md
_workplaces/Kickstarter.md
job-board.md

This PR adds [Democracy Works](https://democracy.works) to the list of union workplaces (its union being [Democracy Workers](https://www.democracyworkers.org), TNG-CWA local 31222).
It also fixes a couple of issues with `job-board.md`:
- typos were preventing links from working
- references to `union_website` were being turned into Twitter timeline links

Add Democracy Works & fix typos

---

_config.yml
join.md
netlify.toml
slack-thanks.md
welcome.md

1. When a user fills out [/subscribe](https://techworkerscoalition.org/subscribe/) they get redirected to a modernized [/welcome](https://deploy-preview-357--techworkersco.netlify.app/welcome), which was formerly /slack-thanks 
2. An expanded explanation of what happens after completing the form, the two auto-subscribes and conditional/manual slack invitation

Make it more transparent what to expect after signing up

---

index.md

https://data.collectiveaction.tech/ has moved over to airtable, need to analyze how to reimport/use this database :D for now remove defunct github data source

remove collective action in tech external link

---

_includes/event-card.html
_includes/head.html
admin/config.yml

* If an event has an image attribute, e.g from Berlin events it will now render those
* Enable explicit image to be set, which can be different from image rendered in body
* Refactor image search logic to be more clear
Sometimes image is silly, but that can be fixed by setting an explicit event image in such a case that is fit for 100x100px and or looks good when cover-position centered (css)

Improve event images

---

_i18n/en/guide.md
_i18n/fr/guide.md
_i18n/pt/guide.md
chapter_local/london.md

Remove Slack channel guides, as per [Slack thread](https://techworkersco.slack.com/archives/C04MYU5NY5P/p1741371060427679?thread_ts=1741314827.419889&cid=C04MYU5NY5P).
Added a log dated for March 8th as that's when I believe this pull request will be merged.

Remove Slack channel guides

---

_config.yml
_includes/events.html
_plugins/get_data.rb

Adds events from English events listed in https://techwerkers.nl/en/events/ to the https://techworkerscoalition.org/events/ and homepage (of
upcoming events). I do think the generic TWC Netherlands image could be more clear, that it's Netherlands chapter. 
Example screenshot of Dutch events on TWC Global page now available

add Dutch events to global website

---

_config.yml

https://github.com/techworkersco/twc-site-nl/pull/112 will create a new path for twc-global specific layouts etc.
Helps us to keep the code organised when there are specific layouts needed for twc-global
The yaml: https://deploy-preview-112--twc-site-nl.netlify.app/en/twc-global/index.yaml

Move twc-nl events sourcing from a twc-global specific page

---

chapter_local/sf-bay-area.md
join.md

- Remove the google form which we're deprecating now that chapter tagging happens automatically in the "Join" form
- Update the 1:1 checkbox to specify someone "from TWC" will reach out, not set expectation that it will be a local chapter member.

Update Bay Area onboarding language

---

_data/chapters.yaml
_i18n/en.yml
chapter_local/austin.md
chapter_local/chicago.md
chapters.md
join.md

- "midactive" -> "semiactive" activity level to fix logic
- Include semiactive chapters in /subscribe dropdown
- Add facebook pages to chapter page
- Remove all dead chapter links
- Link to chapter page from homepage

Chapter cleanups, remove dead links

---

Gemfile
Gemfile.lock

We use the [TZInfo gem][0] for timezone data. To quote its docs:
> By default, TZInfo will attempt to use TZInfo::Data. If TZInfo::Data is not available, then TZInfo will search for a zoneinfo directory instead.
We weren't using `TZInfo::Data`, so we were at the mercy of the system's zoneinfo database.
My system lacked at least one of the timezones we use, `US/Pacific`, so I got this error when running `jekyll serve` (reformatted slightly):
.../gems/tzinfo-2.0.6/lib/tzinfo/data_source.rb:321:
in 'TZInfo::DataSource#validate_timezone_identifier':
Invalid identifier: US/Pacific (TZInfo::InvalidTimezoneIdentifier)
This installs the `tzinfo-data` gem to stop using the system zoneinfo.
This fixed my problem, but I also think this is a useful change for others. Now everyone can rely on the same …

Include timezone data for consistency
